---
title: "Statistical_Rethinking06"
author: "Robert A. Stevens"
date: "May 4, 2016"
output: html_document
---

*Statistical Rethinking: A Bayesian Course with Examples in R and Stan*

by Richard McElreath

# 6.0 Overfitting, Regularization, and Information Criteria  

Figure 6.1. Ptolemaic (left) and Copernican (right) models of the solar system. Both models use epicycles (circles on circles), and boht models produce exactly the sampe predictions. However, the Copernican modle requires fewer circles. (Not all Ptolemaic epicycles are visible in the figure.)

Rethinking: Stargazing.

Rethinking: Is AIC Bayesian?

## 6.1 The problem with parameters  

### 6.1.1 More parameters always improve fit

Figure 6.2. Average brain volume in cubic centimeters against body mass in kilograms, for six hominin species. What model best describes the relationship between brain size and body size?

R code 6.1

R code 6.2

R code 6.3

R code 6.4

R code 6.5

Figure 6.3. Polynomial linear models of increasing degree, fit to the hominin data. Each plot shows the predicted mean in black, with 89% interval of the mean shaded. R^2, is displayed above each plot. (a) First-degree polynomial. (b) Second-degree. (c) Third-degree. (d) Fourth-degree. (e) Fifth-degree. (f) Sixth-degree.

Rethinking: Model fitting as compression

### 6.1.2 Too few parameters hurts, too

R code 6.6

Figure 6.4. An underfit model of hominin brain volume. This model ignores any association between body mass and brain volume, producing a horizontal line of predictions. As a result, the model fits badly and (presumably) predicts badly.

Figure 6.5. Underfitting and overfitting as under-sensitivity and over-sensitivity to sample. In both plots, a regression is fit to the seven sets of data made by dropping one row from the original data. (a) An underfit model is insensitive to the sample, changing as individual points are dropped. (b) An overfit model is sensitive to the sample, changing dramatically as points are dropped.

Overthinking: Dropping rows

R code 6.7

R code 6.8

Rethinking: Bias and variance

## 6.2 Information theory and model performance  

### 6.2.1 Firing the weatherperson

#### 6.2.1.1 Costs and benefits

#### 6.2.1.2 Measuring accuracy

Rethinking: What is a true model?

### 6.2.2 Information and uncertainty

R code 6.9

Overthinking: More on entropy

Rethinking: The benefits of maximizing uncertainty

### 6.2.3 From entropy to accuracy

Figure 6.6 Information divergence of an approximating distribution q from a true distribution p. Divergence can only equal zero when q = p (dashed line). Otherwise, the divergence is positive and grow as q becomes more dissimilar from p. When we have more than one candidate approximation q, the q with the smallest divergence is the most accurate approximation, in the sense taht it induces the least additional uncertainty.

Overthinking: Cross entropy and divergence

Rethinking: Divergence depends upon direction

### 6.2.4 From divergence to deviance

R code 6.10

Overthinking: Computing deviance

R code 6.11

### 6.2.5 From deviance to out-of-sample

Figure 6.7. Deviance in and out of sample. In each plot, models with different numbers of predictor variables are shown on the orizontal axis. Deviance across 10,000 simulations is show on the vertical. Blue shows deviance in-sample, the training data. Black shows deviance out-of-sample, the test data. Points show means, and the line segments show +/- 1 stnandard deviation.

Overthinking: Simulated training and testing

R code 6.12

R code 6.13

R code 6.14

## 6.3 Regularization  

Figure 6.8. Regularizing priors, weak and strong. Three Gaussian priors of varying standard deviation. These priors reduce overfitting, but with different strength. Dashed: Normal(0, 1). Thin solid: Normal(0, 0.5). Thick solid: Normal(0, 0.2).

Figure 6.9. REgularizing priors and out-of-sample deviance. The points in both plots are the same as in Figure 6.7. The lines show training (blue) and testing (black) deviance for the three regularizing priors in Figure 6.8. Dashed: Each beta-coefficient is given a Normal(0, 1) prior. Thin solid: Normal(0, 0.5). Thick solid: Normal(0, 0.2).

Rethinking: Multilevel models as adaptive regularization

Rethinking: Ridge regression

## 6.4 Information criteria  

Figure 6.10. Deviance in-sample (blue) and out-of-sample (black), using flat priors. The vertical segments measure the distance between each pair of deviance. For both N = 20 and N = 100, this distance is approximately twice the number of parameters. The dashed lines show exactly the deviance in-sample (training) plus twie the number of parameters on the horizontal axis. These lines therefore show AIC for each model, an approximation of the out-of-sample deviance.

Rethinking: Information criteria and consistency

### 6.4.1 DIC

### 6.4.2 WAIC

Rethinking: What about BIC?

Overthinking: WAIC calculations

R code 6.15

R code 6.16

R code 6.17

R code 6.18

R code 6.19

R code 6.20

### 6.4.3 DIC and WAIC as estimates of deviance

Figure 6.11. Out-of-sample deviance as estimated by DIC and WAIC. Points are average out-of-sample deviance over 10,000 simulations. The lines are average DIC (top) and WAIC (bottom) computed from the same simulations. The black points and lines come from simulations with a nearly flat Normal(0, 100) prior. The blue points and lines used a regularzing Normal(0, 0.5) prior.

Rethinking: Diverse prediction framework

## 6.5 Using information criteria  

### 6.5.1 Model comparison

R code 6.21

R code 6.22

#### 6.5.1.1 Comparing WAIC values

R code 6.23

R code 6.24

R code 6.25

R code 6.26

Rethinking: How big a difference in WAIC is "significant"?

Rethinking: WAIC metaphors

#### 6.5.1.2 Comparing estimates

R code 6.27

R code 6.28

Figure 6.12. Comparing the posterior densities of parameters for the four model fits to the primate milk data. Each point is a MAP estiatme, and each black line segment is a 89% percentile interval. Estimates are grouped by parameter identify, and each row in a group is a model.

Rethinking: Barplots suck

### 6.5.2 Model averaging

R code 6.29

Figure 6.13. Model averaged posterior predictive distribution for the primate milk analysis. The dashed regression line and dashed 89% percentile interval corresponed to the minimum-WAIC model, m6.14. The solid line and shaded 89% region correspond to the model averaged predictions.

R code 6.30

Rethinking: The Curse of Tippecanoe

## 6.6 Summary  

## 6.7 Practice  

6E1

6E2

6E3

6E4

6M1

6M2

6M3

6M4

6M5

6M6

R code 6.31

6H1

6H2

6H3

6H4

R code 6.32

6H5

6H6
