---
title: "Statistical_Rethinking04"
author: "Robert A. Stevens"
date: "May 4, 2016"
output: html_document
---

```{r, comment=NA}
library(rethinking)
library(StanHeaders)
```

*Statistical Rethinking: A Bayesian Course with Examples in R and Stan*

by Richard McElreath

# 4.0 Linear Models  

Figure 4.1. The Ptolemaic Universe, in which complex motion of the planets in the night sky was explained by orbits within orbits, called epicycles. The model is incredibly wrong, yet makes quite good predictions.

## 4.1 Why normal distributions are normal  

### 4.1.1 Normal by addition

R code 4.1

Figure 4.2. Random walks on the soccer field converge to a normal distribution. The more steps are taken, the closer the match between the real empirical distribution of positions and the ideal normal distribution, superimposed in the last plot in the bottom panel.

### 4.1.2 Normal by multiplication

R code 4.2

R code 4.3

R code 4.4

### 4.1.3 Normal by log-multiplication

R code 4.5

### 4.1.4 Using Gaussian distributions

#### 4.1.4.1 Ontological justification

#### 4.1.4.2 Epistemological justification

Overthinking: Gaussian distribution

## 4.2 A language for describing models  

### 4.2.1 Rd-describing the globe tossing model

Overthinking: From model definition to Bayes' theorem

R code 4.6

## 4.3 A Gaussian model of height  

### 4.3.1 The data

R code 4.7

R code 4.8

R code 4.9

Overthinking: Data frames

R code 4.10

Overthinking: Index magic

### 4.3.2 The model

Rethinking: Independent and identically distributed

R code 4.11

R code 4.12

Rethinking: A farewell to epsilon

Overthinking: Model definition to Bayes' theorem again

### 4.3.3 Grid approximation of the posterior distribution

R code 4.14

R code 4.15

R code 4.16

### 4.3.4 Sampling from the posterior

R code 4.17

R code 4.18

R code 4.19

R code 4.20

Overthinking: Sample size and the normality of sigma's posterior

R code 4.21

R code 4.22

R code 4.23

### 4.3.5 Fitting the model with map

R code 4.24

R code 4.25

R code 4.26

R code 4.27

Overthinking: Start values for map

R code 4.28

R code 4.29

Overthinking: How strong is a prior?

### 4.3.6 Sampling from a map fit

R code 4.30

R code 4.31

R code 4.32

R code 4.33

Overthinking: Under the hood with multivariate sampling

R code 4.34

Overthinking: Getting sigma right

R code 4.35

R code 4.36

## 4.4 Adding a predictor  

R code 4.37

Rethinking: What is "regression"

### 4.4.1 The linear model strategy

#### 4.4.1.1 Likelihood

#### 4.4.1.2 Linear model

Rethinking:  Nothing special or natural about linear models

Overthinking: Units and regression models

#### 4.4.1.3 Priors

Rethinking: What's the correct prior?

### 4.4.2 Fitting the model

R code 4.38

Rethinking: Everything that depends upon parameters has a posterior distribution.

Overthinking: Embedding linear models

R code 4.39

### 4.4.3 Interpreting the model fit

Rethinking: What do parameters mean?

#### 4.4.3.1 Tables of estimates

R code 4.40

R doce 4.41

R code 4.42

R code 4.43

R code 4.44

#### 4.4.3.2 Plotting posterior inference against the data

R code 4.45

#### 4.4.3.3 Adding uncertainty around the mean

Figure 4.4. Height in centimeteres (vertical) plotted agains weight in kilograms (horizontal), with the maximum a posteriori line for the mean height at each weight plotted in black.

R code 4.46

R code 4.47

R code 4.48

R code 4.49

Figure 4.5. Samples from the quadratic approximate posterior distribution for the height/weight model, m4.3, with increasing amounts of data. In each plot, 20 lines sampled fro the posterior distribution, showing the uncertainty in the regression relationship. 

#### 4.4.3.4 Plotting regression intervals and contours

R code 4.50

R code 4.51

Figure 4.6. The quadratic approximate posterior distribution of the mean height, m, where weight is 50 kg. This distribution represents the relative plausibility of different values or the mean.

R code 4.52

R code 4.53

R code 4.54

R code 4.55

Figure 4.7. Left: The first 100 value sin the distribution of m at each weight value. Right: The !Kung height data again, now with 89% HPDI of the mean indicated by the shaded region. Compare this region to the distributions of blue points on the left.

R code 4.56

R code 4.57

Rethinking: Overconfident confidence intervals

Overthinking: How link works

R code 4.58

#### 4.4.3.5 Prediction intervals

R code 4.59

R code 4.60

R code 4.61

Figure 4.8. 89% prediction interval for height, as a function of weight. The solid line is the MAP estimate of the mean height at each weight. The tow shaded regions show different 89% plausible regions. The narrow shaded interval around the line is the distribution of m. The wider shaded region represents the region within which the model expects to find 89% of actual heights in the population, at each weight.

R code 4.62

Rethinking: Two kinds of uncertainty

Overthinking: Rolling your own sim.

R code 4.63

## 4.5 Polynomial regression  

R code 4.64

Rethinking: Linear, additive, funky.

R code 4.65

R code 4.66

R code 4.67

R code 4.68

R code 4.69

Figure 4.9. Polynomial regression of height on weight (standardized), for the full !Kung data. In each plot, the raw data are show by the circles. The solid curves show the path of m in each model, and the shaded regions show the 89% interval of the mean (close to the solid curve) and the 89% interval of predictions (wider). (a) Linear regression. (b) A second order polynomial, a parabolic regression. (c) A third order polynomial, a cubic regression.

R code 4.70

Overthinking: Converting back to natural scale.

R code 4.71

R code 4.72

## 4.6 Summary  

## 4.7 Practice  

4E1

4E2

4E3

4E4

4E5

4M1

4M2

4M3

4M4

4M5

4M6

4H1

4H2

4H3

R code 4.73
