---
title: "Statistical_Rethinking11"
author: "Robert A. Stevens"
date: "May 4, 2016"
output: html_document
---

*Statistical Rethinking: A Bayesian Course with Examples in R and Stan*

by Richard McElreath

**TODO:**

1. Add R code and format

2. Run R code and check

3. Do practice problems

# 11.0 Monsters and Mixtures  

## 11.1 Ordered categorical outcomes  

### 11.1.1 Example: Moral intuition

R code 11.1

### 11.1.2 Desribing an ordered distribution with intercepts

R code 11.2

Figure 11.1. Re-descibing a discrete distribution using log-cumulative odds. Left: Histogram of discrete response in the sample. 

R code 11.3

Figure 11.1. Re-descibing a discrete distribution using log-cumulative odds. Middle: Cumulative proportion of each response. 

R code 11.4

Figure 11.1. Re-descibing a discrete distribution using log-cumulative odds. Right: Logarithm of cumulative odds of each response. Note that the log-cumulative-odds of response value 7 is infinity, so it is not shown.

Figure 11.2. Cumulative probability and ordered likelihood. The horzontal axis displays possible observable outcomes, from 1 through 7. The vertical axis displays cumulative probability. The gray bars over each outcome show cumulative probability. These keep growing with each successive outcome value. The blue line segments show the discrete probability of each individual otucome. These are the likelihoods that go into Bayes' theorem.

R code 11.5

R code 11.6

R code 11.7

R code 11.8

### 11.1.3 Adding predictor variables

R code 11.9

R code 11.10

R code 11.11

R code 11.12

R code 11.13

R code 11.14

R code 11.15

R code 11.16

R code 11.17

R code 11.18

R code 11.19

Figure 11.3. Posterior predictions of the ordered categorical model with interactions, m11.3. Each plot shows how the distribution of predicted responses varies by intention. Left: Effect of intention when action and contact are both zero. The other two plots each change either action or contact to one.

Rethinking: Staring into the abyss

## 11.2 Zero-inflated outcomes  

Rethinking: Breaking the law

### 11.2.1 Example: Zero-inflated Poisson

R code 11.20

R code 11.21

Figure 11.4. Left: Structure of the zero-inflated likelihood calculation. Beginning at the top, the monks drink p of the time or or instead work 1 - p of the time. Drinking monks always produce an observation y = 0. Working monds may produce either y = 0 or y > 0. Right: Frequency distribution of zero-inflated observations. The blue line segment over zero shows the y = 0 observations that arose from drinking. In real data, we typically cannot see which zeros come from which processes.

R code 11.22

R code 11.23

Overthinking: Zero-inflated Poisson distribution function

R code 11.24

## 11.3 Over-dispersed outcomes  

### 11.3.1 Beta-binomial

R code 11.25

R code 11.26

R code 11.27

R code 11.28

R code 11.29

Figure 11.5. Left: Posterior distribution of beta distributions for m11.5. The thick curve is the posterior mean beta distribution. The lighter curves represent 100 combinations of p and Theta sampled from the posterior.

R code 11.30

Figure 11.5. Right: Posterior validation check for m11.5. As a result of the widely dispersed beta distributions on the left, the raw data (blue) is contained within the prediction intervals.

### 11.3.2 Negative-binomial or gamma-Poisson

R code 11.31

### 11.3.3 Over-dispersion, entropy, and information criteria

Overthinking: Continuous mixtures

## 11.4 Summary  

## 11.5 Practice  

11E1.

11E2.

11E3.

11E4.

11M1.

11M2.

11M3.

11H1.

R code 11.32

11H2.

11H3.

11H4.

11H5.

11H6.
