---
title: "Statistical_Rethinking08"
author: "Robert A. Stevens"
date: "May 4, 2016"
output: html_document
---

*Statistical Rethinking: A Bayesian Course with Examples in R and Stan*

by Richard McElreath

# 8.0 Markov Chain Monte Carlo  

Rethinking:  Stan was a man

## 8.1 Good King Markov and His island kingdom  

Figure 8.1. Good King Markov's island kingdom. Each of the 10 islands has a population proportional to its number, 1 through 10. The King's goal is to visit each island, in the long run, in proportion to its population size. This can be accomplished by the Metropolis algorithm.

R code 8.1

Figure 8.2. Results of the king following the Metropolis algorithm. The left-hand plot shows the king's position (veritical axis) across weeks (horizontal axis). In any particular week, it's nearly impossible to say where the king will be. The right-hand plot shows the long-run behavior of the algorithm, as the time spent on each island turns out to be proportional to its population size.

## 8.2 Markov chain Monte Carlo  

### 8.2.1 Gibbs sampling

### 8.2.2 Hamiltonian Monte Carlo

Rethinking:  The MCMC horizon

## 8.3 Easy HMC: map2stan  

R code 8.2

R code 8.3

### 8.3.1 Preparation

R code 8.4

### 8.3.2 Estimation

R code 8.5

R code 8.6

### 8.3.3 Sampling again, in parallel

R code 8.7

### 8.3.4 Visualization

R code 8.8

R code 8.9

R code 8.10

Figure 8.3. Pairs plot of the samples produced by Stan. The diagonal shows a density estiamte for each parameter. Below the diagonal, correlations between parameters are shown.

Overthinking: Stan messages

### 8.3.5 Using the samples

R code 8.11

### 8.3.6 Checking the chain

R code 8.12

Figure 8.4. Trace plot of the Markov chain from the ruggedness model, m8.1stan. This is a clean, healthy Markove chain, both stationary and well-mixing. The gray region is warmup, during which the Markov chain was adapting to improve sampling efficiency. The white region contains the samples used for inference.

Overthinking: Raw Stan model code

## 8.4 Care and feeding of your Markov chain  

### 8.4.1 How many samples do you need?

Rethinking: Warmup is not burn-in

### 8.4.2 How many chians do you need?

Rethinking: Convergence diagnostics

### 8.4.3 Taming a wild chain

R code 8.13

R code 8.14

Figure 8.5. Diagnosing and healing a sick Markov chain. Top row: Trace plot from two independent chains defined by model m8.2. These chains are not stationary and should not be used for inference. Bottom row: Adding weakly informative priors (see m8.3) clears up the conditional right away. These chains are fine to use for inference.

R code 8.15

Figure 8.6. Prior (dashed) and posterior (blue) for the model with weakly informative priors, m8.3. Even with only two observations, the likelihood easily overcomes these priors. Yet the model cannot be successfully estimated without them.

Overthinking: Cauchy distribution

R code 8.16

### 8.4.4 Non-identifiable parameters

R code 8.17

R code 8.18

R code 8.19

Figure 8.7. Left column: A chain with wandering parameters, a1 and a2, generated by m8.4. Right column: Same model but now with weakly informative priors, m8.5.

## 8.5 Summary  

## 8.6 Practice  

8E1

8E2

8E3

8E4

8E5

8E6

8M1

8M2

8M3

8H1

R code 8.20

8H2

8H3

R code 8.21

R code 8.22

R code 8.23

8H4

8H5

8H6
